# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_QCOM) += \
	qcom-apq8064-cm-qs600.dtb \
	qcom-apq8064-ifc6410.dtb \
	qcom-apq8064-sony-xperia-lagan-yuga.dtb \
	qcom-apq8064-asus-nexus7-flo.dtb \
